### ISSUE TITLE
Object Detection bounding boxes shifted by constant amount in UI

### ISSUE THREAD

**Issue by maxkazmsft** [Azure-Samples/cognitive-services-python-sdk-samples#36]
Bounding boxes are not located in the right places and need to be offset by roughly 0.04 relative units to the left and 0.07 relative units up on upload (see code below). Some images have bounding boxes appear in completely wrong places, but this does not happen often.

The quick fix which we used was to offset all bounding boxes in the API and make them slightly larger. Those boxes which still didn't have the right location were adjusted manually.

Code:
```python
if args.detect:
    # read the tag location from VOC file
    voc_filename = image_inpath.split(".")[0] + ".txt"
    if not os.path.exists(voc_filename):
        print(
            "You want to run object detection but haven't tagged",
            voc_filename,
        )
        quit(1)

    with open(voc_filename) as fd:
        lines = [x.rstrip("\n").split(" ") for x in fd.readlines()]

    regions = [
        Region(
            tag_id=tag_connector.id,
            left=map_x(float(x[1]) - 0.04),
            top=map_y(float(x[2]) - 0.07),
            width=width(float(x[3]) + 0.02),
            height=height(float(x[4]) + 0.02),
        )
        for x in lines
    ]
    tag = tag_connector

else:
    tag = tag_good if df[LABEL_COL].iloc[i] in GOOD_SET else tag_bad

with open(image_outpath, mode="rb") as image:
    image_content = image.read()

image = ImageFileCreateEntry(
    name=image_outpath.split("/")[-1],
    contents=image_content,
    tag_ids=[tag.id],
)

if args.detect:
    image.regions = regions

trainer.create_images_from_files(project.id, images=[image])
```

We have to loop through uploaded images and manually shift the bounding boxes to the correct location for some images. For most images the fix above of shifting the image on upload works for now, but regardless we shouldn't be doing it. This manual verification has to be performed before training . Doing such manual procedure is not possible for large training set sizes of over 30 images.

This looks like an SDK issue when talking to the back-end service.

**Comment by lmazuel** [comment]
@areddish ?

**Comment by areddish** [comment]
@maxkazmsft Are you saying you have to make this shift for them to appear correctly in the portal UI?

**Comment by maxkazmsft** [comment]
@areddish yes, and in 10% of the images the bounding box appears in an almost random place in the UI. The code shows the fix - make the boxes shifted and a bit larger.

**Comment by socpool** [comment]
@maxkazmsft Thanks for the response - what I'm trying to figure out is if the data is being changed in the service or if it's just not rendering correctly in the portal.

Have you tried retrieving the image regions to see if they are different after submission?
Also, what kind of image sizes are being sent?

I'll do some investigation on my side to try and reproduce the issue.

**Comment by areddish** [comment]
@maxkazmsft Thanks for the response - what I'm trying to figure out is if the data is being changed in the service or if it's just not rendering correctly in the portal.

Have you tried retrieving the image regions to see if they are different after submission?
Also, what kind of image sizes are being sent?

I'll do some investigation on my side to try and reproduce the issue.

**Comment by areddish** [comment]
I confirmed that what I sent to the service comes back. So the data transfer is correct.

**Comment by wiazur** [comment]
@areddish is this issue still being worked on? Sounds like it's an Azure portal issue. If so, we can close this out here. Thanks.
