### ISSUE TITLE
Commit with [DO NOT MERGE] in master

### ISSUE THREAD

**Issue by lawrencegripper** [Azure-Samples/cognitive-services-python-sdk-samples#38]
![surethisisfine](https://user-images.githubusercontent.com/1939288/55969118-2993ec80-5c75-11e9-83fe-c4b3cf4d55b2.jpg)

Seems a bit like this shouldn't be in the `master` branch - was this an accident?

Commit: https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/commit/ed27a9f33f5dc60a3deab7f26435aafa50f0db9d

**Comment by anrothMSFT** [comment]
@nitinme fyi

**Comment by lawrencegripper** [comment]
Also looks like all the builds are failing https://travis-ci.org/Azure-Samples/cognitive-services-python-sdk-samples/branches

**Comment by lmazuel** [comment]
Gone, so closing the issue, but I agree in an ideal we should rename a PR before merging, or better use a Github label "Do not merge"
