### ISSUE TITLE
Image batch upload failed

### ISSUE THREAD

**Issue by ericjiang18** [Azure-Samples/cognitive-services-python-sdk-samples#56]
I've try to upload image 

But returns:
Adding images...
Image batch upload failed.
Image status:  ErrorUnknown
Image status:  ErrorUnknown
Image status:  ErrorUnknown
Image status:  ErrorUnknown
...
I've the status of upload_result and print these information below:

{'additional_properties': {}, 'is_batch_successful': False, 'images': [<azure.cognitiveservices.vision.customvision.training.models.image_create_result_py3.ImageCreateResult object at 0x107cc4630>, <azure.cognitiveservices.vision.customvision.training.models.image_create_result_py3.ImageCreateResult object at 0x107cc4780>

Is there anyway to fix this and to upload my images successfully?

**Comment by areddish** [comment]
Hi @ericjiang18 , There should be some additional information in the status field of the images in the batch returned. i.e. if using the sample code:

```
if not upload_result.is_batch_successful:
    print("Image batch upload failed.")
    for image in upload_result.images:
        print("Image status: ", image.status)
```

I'm curious what the status says.

**Comment by ericjiang18** [comment]
That is really strange!


The code I am using is:
for i in range(0,len(tagged_images_with_regions),64):
    batch = tagged_images_with_regions[i:i+64]
    #print(batch)
    upload_result = trainer.create_images_from_files(project.id, images=batch)
    print(upload_result)
    if not upload_result.is_batch_successful:
        print("Image batch upload failed.")
    for image in upload_result.images:
        print("Image status: ", image.status)
    exit(-1)

However the terminal print:
Creating project...
Adding images...
{'additional_properties': {}, 'is_batch_successful': False, 'images': [<azure.cognitiveservices.vision.customvision.training.models.image_create_result_py3.ImageCreateResult object at 0x1030047b8>, <azure.cognitiveservices.vision.customvision.training.models.image_create_result_py3.ImageCreateResult object at 0x1030047f0>, <azure.cognitiveservices.vision.customvision.training.models.image_create_result_py3.ImageCreateResult object at 0x103004be0>...
}
Image batch upload failed.
Image status:  ErrorUnknown
Image status:  ErrorUnknown
Image status:  ErrorUnknown

**Comment by ericjiang18** [comment]
@areddish

**Comment by ericjiang18** [comment]
@YutongTie-MSFT

**Comment by areddish** [comment]
Can you show the code that is creating one of the ImageFileCreateEntry? Usually ErrorUnknown has something to do with the contents field of the ImageFileCreateEntry. It typically means we can't determine what the data is in the content field.

**Comment by ericjiang18** [comment]
Here is the code
`
for file_name in bus_stop_image_regions.keys():

    x,y,w,h = bus_stop_image_regions[file_name]

    regions = [ Region(tag_id=bus_stop_tag.id, left=x,top=y,width=w,height=h) ]

    with open("/Users/broccoli/Desktop/mturk_516/" + file_name + ".jpg", mode="rb") as image_contents:

        tagged_images_with_regions.append(ImageFileCreateEntry(name=file_name, contents=image_contents.read(), regions=regions))


`

**Comment by ericjiang18** [comment]
The tagged_images_with_regions print: [<azure.cognitiveservices.vision.customvision.training.models.image_file_create_entry_py3.ImageFileCreateEntry object at 0x10b9e42b0>] etc. 

the ImageFileCreateEntry print:
<class 'azure.cognitiveservices.vision.customvision.training.models.image_file_create_entry_py3.ImageFileCreateEntry'> etc.

**Comment by areddish** [comment]
Another thing to check is the bus_stop_tag.id - you can get ErrorUnknown if the tag can't be found or you use a tag id from a different project. To check you can add this code just before uploading images

```Python
t = trainer.get_tag(project.id, bus_stop_tag.id)
print("Found",t.name,"with id = ",t.id)
```

It will return a CustomVisionErrorException if the tag isn't found.

**Comment by ericjiang18** [comment]
I think it is the problem: 

 File "Training.py", line 34, in <module>
    t = trainer.get_tag(project.id, bus_stop_tag.id)
  File "/Users/broccoli/Desktop/bus_stop_sign_detection-master/code/env/lib/python3.7/site-packages/azure/cognitiveservices/vision/customvision/training/custom_vision_training_client.py", line 2510, in get_tag
    raise models.CustomVisionErrorException(self._deserialize, response)
azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionErrorException: Tag not found

**Comment by ericjiang18** [comment]
So what should I do?

**Comment by areddish** [comment]
Depends on how you are running the code. If you are creating the project and tag each time you run, then you should be ok as you should be using the return of **create_tag**. 

If you are adding images to the project after it's created it's better to look up the tag each time. Something like this:

```Python
project_tags = trainer.get_tags(project.id)
bus_stop_tag = next(filter(lambda t: t.name == "bus stop", project_tags))
```
_Replacing **bus stop** with the name of the tag_

**Comment by ericjiang18** [comment]
It returns: StopIteration

**Comment by areddish** [comment]
StopIteration means either the project_tags was an empty list or that it didn't find the tag in the project. You could dump out all of the tags and to see what's in the project:

```Python
project_tags = trainer.get_tags(project.id)
print ("Found", len(project_tags), "tag(s)")
for t in project_tags:
    print(t.name, t.id)
```

**Comment by ericjiang18** [comment]
I got it! When it runs, some print:
Image status:  ErrorUnknown
Image status:  OK
Image status:  OKDuplicate
Image status:  OK
Image status:  OKDuplicate
Image status:  OKDuplicate
Image status:  ErrorUnknown

**Comment by areddish** [comment]
OKDuplicate means that it's the same image as one already in the project. So it should just add that region to the original image. You can avoid that by adding more than one region into the regions array you pass into ImageFileCreateEntry

I would suspect the ErrorUnknown ones are sending a tag id that can't be found in the project. I'll file an internal task to add an ErrorTagNotFound or something to make it more easy to debug in the future.

**Comment by ericjiang18** [comment]
Got it! It all works fine!
Huge Thanks!

**Comment by nikhilnaregal** [comment]
Hello  @areddish , I had a similar problem while uploading. (Image status: OKDuplicate) . Can you please what exactly array should I pass for regions??
```
image_list = []
    i = -1

    # Uses subfolder names to create labels
    for folder_name in list_subfolders_with_names:
        i += 1
        tag = trainer.create_tag(project.id, list_subfolders_with_names[i])
        for image_file in os.listdir(START_PATH + "/{}".format(folder_name)):
            with open(START_PATH + "/" + folder_name + "/{}".format(image_file), "rb") as image_contents:
                image_list.append(
                    ImageFileCreateEntry(name=image_file, contents=image_contents.read(), tag_ids=[tag.id]))
```
