### ISSUE TITLE
Does anyone used video add frames using stream (Python)

### ISSUE THREAD

**Issue by kunalg06** [Azure-Samples/cognitive-services-python-sdk-samples#74]
Hello Guys,

Need help to call below method,
client.reviews.add_video_frame_stream(content_type="image/jpeg", team_name="xyz", review_id=review_id, frame_image_zip='/Sample_1.zip', frame_metadata='', timescale=None, custom_headers=None, raw=False)

Can anyone help to understand what parameter I am sending wrong?
I am always getting "Bad Request" when I call this.

Need urgent help.
Thanks in advance.

**Comment by wiazur** [comment]
Hi @kunalg06, could you post your full stacktrace? Thanks.

**Comment by wiazur** [comment]
@kunalg06, looking at the function parameters, I see that the `frame_image_zip` is a Generator object as shown in the [API Reference](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-contentmoderator/azure.cognitiveservices.vision.contentmoderator.operations.reviewsoperations?view=azure-python#add-video-frame-stream-content-type--team-name--review-id--frame-image-zip--frame-metadata--timescale-none--custom-headers-none--raw-false----operation-config-). You have `'/Sample_1.zip'` which is a string. 

To put a zip file into a Generator object, try this snippet:

```
file_name = 'video_frames.zip'
def zip_generator(name):
    for row in open(file_name, "r"):
        yield row

zip_gen_obj = zip_generator(file_name)
print(zip_gen_obj)
```

The print statement is only to show that `zip_gen_obj` is a Generator object after the code is run. Then you can use that variable for the value of `frame_image_zip`.
