### ISSUE TITLE
Object detection( Prediction ) AttributeError: 'CustomVisionPredictionClient' object has no attribute 'predict_image'

### ISSUE THREAD

**Issue by mrsalhaoui** [Azure-Samples/cognitive-services-python-sdk-samples#75]
Hello,

I´m trying to connect my object detection project to my host application, and I've already trained my Model, and I have the iteration id and project ID. I would just like to use the prediction code in my application, I tried to do the same code found [here](https://github.com/MicrosoftDocs/azure-docs/issues/19907) which is : 

```
! pip install azure-cognitiveservices-vision-customvision
from azure.cognitiveservices.vision.customvision.prediction import CustomVisionPredictionClient

my_project_id = "Project Id from the settings page" 
prediction_key = "Prediction Key from the settings page"

ENDPOINT = "https://southcentralus.api.cognitive.microsoft.com"
predictor = CustomVisionPredictionClient(prediction_key, endpoint=ENDPOINT)
my_iteration_id = "iteration id from portal"

with open("Swimming/14.jpg", mode="rb") as test_data:
    results = predictor.predict_image(my_project_id, test_data, iteration_id=my_iteration_id)
```
but, I still receiving this error : 

> Traceback (most recent call last):
>   File "cazurecloud.py", line 22, in <module>
>     results = predictor.predict_image(my_project_id, test_data, iteration_id=my_iteration_id)
> AttributeError: 'CustomVisionPredictionClient' object has no attribute 'predict_image'

Any Help, please !

**Comment by mrsalhaoui** [comment]
I changed predict_image function to detect_image following this [link](https://docs.microsoft.com/en-us/azure/cognitive-services/custom-vision-service/python-tutorial-od#get-the-training-and-prediction-keys), but I still have this error : 

```
Traceback (most recent call last):
  File "cazurecloud.py", line 11, in <module>
    results = predictor.detect_image(my_project_id, my_iteration_id, test_data)
  File "C:\Users\Salhaoui\AppData\Local\Programs\Python\Python35-32\lib\site-packages\azure\cognitiveservices\vision\customvision\prediction\custom_vision_prediction_client.py", line 492, in detect_image
    raise models.CustomVisionErrorException(self._deserialize, response)
  File "C:\Users\Salhaoui\AppData\Local\Programs\Python\Python35-32\lib\site-packages\azure\cognitiveservices\vision\customvision\prediction\models\custom_vision_error_py3.py", line 118, in __init__
    super(CustomVisionErrorException, self).__init__(deserialize, response, 'CustomVisionError', *args)
  File "C:\Users\Salhaoui\AppData\Local\Programs\Python\Python35-32\lib\site-packages\msrest\exceptions.py", line 166, in __init__
    self.error = deserialize.dependencies[resp_type]()
TypeError: __init__() missing 2 required keyword-only arguments: 'code' and 'message'
```

**Comment by v-jaswel** [comment]
Hi mrsalhaoui,

Thank you for using Custom Vision and I apologize for the slow reply. I am able to reproduce the error you are seeing, and am investigating. I will keep you posted.
Thank you,
v-jaswel

**Comment by v-jaswel** [comment]
Hi mrsalhaoui,

I am able to run the following code:

```
from azure.cognitiveservices.vision.customvision.prediction import CustomVisionPredictionClient

my_project_id = "<project ID>" 
prediction_key = "<prediction key>"

ENDPOINT = "<endpoint>"
predictor = CustomVisionPredictionClient(prediction_key, endpoint=ENDPOINT)
my_iteration_name = "Iteration1"

with open("<path to test image>", mode="rb") as test_data:
	results = predictor.detect_image(project_id=my_project_id, published_name=my_iteration_name, image_data=test_data)

print (results)
```

1. I named the parameters to detect_image to make sure there was no confusion about the order. The [documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/custom-vision-service/python-tutorial-od#get-the-training-and-prediction-keys) seems to differ from [Github](https://github.com/Azure/azure-sdk-for-python/blob/33c8614005d60e7991ff6ed21e78b1c608f35a51/sdk/cognitiveservices/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/prediction/custom_vision_prediction_client.py#L433) as to what the parameters are.

2. In that link you posted, I found this [post](https://github.com/MicrosoftDocs/azure-docs/issues/19907#issuecomment-445171964) to be helpful.

I was using the iteration ID (a GUID) as the value to the published_name parameter, when I should have been using the iteration name.

To get the iteration name:

1. In customvision.ai, click "Performance" at the top.
1. Click "Prediction URL". If it is disabled, click "Publish". Enter an Iteration name and submit.
1. Nothing might happen at first, but after a few moments the page should refresh and now "Prediction URL" should be enabled.
1. Click "Prediction URL".
1. Use the Iteration name (for example, "Iteration1"), not the Iteration Id (which is a GUID), as the value for the published_name parameter.

Please let me know if this resolves your issue. Thank you!
v-jaswel

**Comment by mrsalhaoui** [comment]
Thank you @v-jaswel  for your answer, but I still getting the same Error  : 

```
Traceback (most recent call last):
  File "cazurecloud.py", line 12, in <module>
    results = predictor.detect_image(project_id=my_project_id, published_name=my_iteration_id, image_data=test_data)
  File "C:\Users\Salhaoui\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\cognitiveservices\vision\customvision\prediction\custom_vision_prediction_client.py", line 492, in detect_image
    raise models.CustomVisionErrorException(self._deserialize, response)
  File "C:\Users\Salhaoui\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\cognitiveservices\vision\customvision\prediction\models\custom_vision_error_py3.py", line 118, in __init__
    super(CustomVisionErrorException, self).__init__(deserialize, response, 'CustomVisionError', *args)
  File "C:\Users\Salhaoui\AppData\Local\Programs\Python\Python36\lib\site-packages\msrest\exceptions.py", line 166, in __init__
    self.error = deserialize.dependencies[resp_type]()
TypeError: __init__() missing 2 required keyword-only arguments: 'code' and 'message'
```

To make sure that the settings are correct and taken properly, I have attached this photo :

![image](https://user-images.githubusercontent.com/33464198/70227274-9606b300-1752-11ea-8ab0-e5aa40ccfdd0.png)

**Comment by v-jaswel** [comment]
Hi @mrsalhaoui, thank you for the detailed screenshot and I am sorry to hear that didn't resolve the issue. I will continue investigating and will try to reproduce those errors you are getting.

**Comment by mrsalhaoui** [comment]
@v-jaswel ! Any updates please for this issue ?

Thank you.

**Comment by v-jaswel** [comment]
Hi @mrsalhaoui, I apologize for the delayed reply.

I feel like that error output might be obscuring what is actually wrong.

Can you please go to the API testing console for the DetectImageUrl method for West Europe:
https://westeurope.dev.cognitive.microsoft.com/docs/services/Custom_Vision_Prediction_3.0/operations/5c82db60bf6a2b11a8247c18/console
and try the following:
1. Enter your projectId.
2. Enter your publishedName (Iteration4)
3. The application can be left blank.
4. Enter your Prediction-Key.
5. In the request body, set the JSON URL value, for example:
```
{
  "url": "https://www.ctvnews.ca/polopoly_fs/1.4516422.1563627119!/httpImage/image.jpg_gen/derivatives/landscape_1020/image.jpg"
}
```
6. Submit and see if you get a 200 OK or some other response.
That should tell us whether the server is objecting to your ID, iteration name, key, etc. I don't see why it would, but it would be good to eliminate that possibility.

I'm still trying to investigate exactly what that error message might mean.
Thank you,
v-jaswel

**Comment by v-jaswel** [comment]
Hi @mrsalhaoui,
Another possibility would be to ensure you have the latest Custom Vision Python package, as follows:

1. Open an Administrator command prompt.
2. Run:
```
pip install --upgrade azure.cognitiveservices.vision.customvision
```

I'm not certain, but I get the feeling there is an error message coming back from the server, and then the Custom Vision package is trying to report it, but is somehow having a problem interpreting it.
Thank you,
v-jaswel

**Comment by mrsalhaoui** [comment]
Thank you @v-jaswel  for your answer, I upgraded the service using your last command, but I still have the same error; furthermore, I tried also the link that you have sent to me, and I received this : 

```
404 Resource Not Found
Response latency
5 ms
```
What do you think @v-jaswel ?

Thank you.

**Comment by v-jaswel** [comment]
Hi @mrsalhaoui,

Can you tell me what is in your Response Content at the bottom when you get that 404?

For example, if I specify an iteration name that I have not yet published, I get:
```
Response status

404 Not Found
Response latency
470 ms 

Response content

Request-Id: ea17c4e8-15b3-4618-aa7c-452cdaf723aa
apim-request-id: ea17c4e8-15b3-4618-aa7c-452cdaf723aa
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
Date: Tue, 10 Dec 2019 23:09:26 GMT
Content-Length: 58
Content-Type: application/json; charset=utf-8

{
  "code": "NotFoundIteration",
  "message": "Invalid iteration"
}
```

**Comment by mrsalhaoui** [comment]
This is the result : 

```
apim-request-id: 2908bab6-fef5-4d33-b055-7b0f030e8d5a
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
Date: Tue, 10 Dec 2019 20:50:16 GMT
Content-Length: 56
Content-Type: application/json

{
  "error": {
    "code": "404",
    "message": "Resource not found"
  }
}
```

**Comment by v-jaswel** [comment]
Thank you - I will try to reproduce that and see what might cause it.

**Comment by v-jaswel** [comment]
Hm, so far I cannot figure out how to get that 404 result, even by submitting various incorrect values.
Can you tell me what is your HTTP request?
Please note you'll want to remove the project ID from the URL and remove the Prediction-Key header value.
For example:

```
HTTP request

POST https://westus2.api.cognitive.microsoft.com/customvision/v3.0/Prediction/<REMOVED PROJECT ID>/detect/iterations/Iteration1/url?application=test HTTP/1.1
Host: westus2.api.cognitive.microsoft.com
Prediction-Key: <REMOVED PREDICTION KEY>
Content-Type: application/json
{
  "url": "https://www.ctvnews.ca/polopoly_fs/1.4516422.1563627119!/httpImage/image.jpg_gen/derivatives/landscape_1020/image.jpg"
}
```

**Comment by mrsalhaoui** [comment]
Ok, this the http request : 

```
POST https://westeurope.api.cognitive.microsoft.com/customvision/v3.0/Prediction/<REMOVED PROJECT ID>/detect/iterations/Iteration4/url HTTP/1.1
Host: westeurope.api.cognitive.microsoft.com
Prediction-Key: <REMOVED PREDICTION KEY>
Content-Type: application/json

{
"url": "https://www.ctvnews.ca/polopoly_fs/1.4516422.1563627119!/httpImage/image.jpg_gen/derivatives/landscape_1020/image.jpg"
}
```
Thank you.

**Comment by areddish** [comment]
Hi @mrsalhaoui,

I believe the problem is with the `my_project_id` value. You don't want to use the Prediction Resource Id, but instead you want to use the ID of the project. This should be a GUID like: `7DA20DB7-AC92-4E21-B26A-252F6374FD39`

You can get that value by going to the portal, clicking on your project, and then clicking on the gear icon to get to the project settings page. Below the project name will be listed the project ID, looks like:

![image](https://user-images.githubusercontent.com/30499261/70677894-54d83c80-1c45-11ea-8719-5ef5332cf37e.png)

Thanks,
Andrew

**Comment by mrsalhaoui** [comment]
Yes finally  it is working, @areddish and @v-jaswel thank you for your help, 

![image](https://user-images.githubusercontent.com/33464198/70720443-1baad580-1cf4-11ea-8e24-9ac902918d60.png)


Thanks,
