### ISSUE TITLE
python websearchapi returns "Operation returned an invalid status code 'Resource Not Found'"

### ISSUE THREAD

**Issue by siminchengithub** [Azure-Samples/cognitive-services-python-sdk-samples#78]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
`subscription_key = "mykey"

client = WebSearchAPI(CognitiveServicesCredentials(subscription_key)
                      , base_url = "https://westeurope.api.cognitive.microsoft.com/"
                     )
client.web.search(query = 'light house company')
`
### Any log messages given by the failure
>
ErrorResponseException: Operation returned an invalid status code 'Resource Not Found'
### Expected/desired behavior
>
Returns search results
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Databricks
### Versions
>

### Mention any other details that might be useful
API type: All Cognitive Services
Pricing tier: standard
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Hi @siminchengithub, did you use all your code from this sample or did you combine code from this with the [quickstart for Web Search](https://docs.microsoft.com/en-us/azure/cognitive-services/bing-web-search/web-sdk-python-quickstart)? This sample uses a different client constructor than the one used in the quickstart. The quickstart's version is old.

I was able to reproduce this error using the quickstart's first version of Web Search:

`client = WebSearchAPI(CognitiveServicesCredentials(key), endpoint)`

The other API calls they make in that quickstart use the client constructor below.

This sample uses:
`client = WebSearchAPI(CognitiveServicesCredentials(subscription_key))`

So when I used that the error was gone and I got full results.

**Comment by wiazur** [comment]
I also added a mute to the logger, so we don't get `Subtype value Organization has no mapping, use base class Thing.` a bunch of times. This can be commented out if someone wishes to include the logger for other reasons.
```
# Comment this logging mute out, if you want to include logging
logger = logging.getLogger()  # get the default logger
logger.setLevel(50)  # set the skip all log which is smaller than critical (50)
```
