### ISSUE TITLE
client.prediction.resolve can't be executed

### ISSUE THREAD

**Issue by jerryzhou0624** [Azure-Samples/cognitive-services-python-sdk-samples#83]
https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/master/samples/language/luis/luis_runtime_samples.py

line 27 "result = client.prediction.resolve" can't be executed 

how to use this sample

**Comment by wiazur** [comment]
Hi @jerryzhou0624, thanks for reporting this. There are several updates needed for that sample. A better place to find a working LUIS example would be to try the quickstart: https://github.com/Azure-Samples/cognitive-services-quickstart-code/tree/master/python/LUIS

It should have the main features of LUIS demonstrated.
