### ISSUE TITLE
azure-cognitiveservices-search-autosuggest>=1.0 doesn't resolve 

### ISSUE THREAD

**Issue by puthurr** [Azure-Samples/cognitive-services-python-sdk-samples#84]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
pip install -r requirements.txt

### Any log messages given by the failure
>
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-search-autosuggest>=1.0 (from -r C:\Users\xxxxxxx\OneDrive\Documents\DataScience\MyExperiments\requirements.txt (line 5)) (from versions: 0.1.0, 0.2.0)
ERROR: No matching distribution found for azure-cognitiveservices-search-autosuggest>=1.0 (from -r C:\Users\xxxxxxx\OneDrive\Documents\DataScience\MyExperiments\requirements.txt (line 5))

### Expected/desired behavior
>
autosuggest library to resolve to 0.2.0

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
@puthurr do you have a code sample to share? I could try to test it. In the past when this error comes up, it often means one version of Python is not working, but another version will work. I have noticed in general that a lot of applications (anywhere, not just Microsoft) are not working yet in Python 3.8. But send your code my way if you still need help. Thanks.

**Comment by puthurr** [comment]
@wiazur : I have no code sample because the issue is with resolving the libraries set in the requirements file : https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/master/requirements.txt 

Using Python 3.6.6 64-bit the pip command "pip install -r requirements.txt" doesn't resolve line 5 
azure-cognitiveservices-search-autosuggest>=1.0 

I could resolve it when I set it to 0.2.0

ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-search-autosuggest>=1.0 (from -r C:\Users\xxxxxxx\OneDrive\Documents\DataScience\MyExperiments\requirements.txt (line 5)) (**from versions: 0.1.0, 0.2.0**)

1.0 dist doesn't exist only 0.1.0 or 0.2.0 do. Could be a typo like a missing 0. in front of 1.0. 

let me know if this helps.

**Comment by wiazur** [comment]
Thank you @puthurr, that did fix the installation issue, I chnaged the file to reflect this. Let us know if you have any other troubles.
